name: "Compile and Test"
on:
  push:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true

      - name: "Checkout submodules"
        run: git submodule update --init

      - name: ShowMe
        run: ls -la

      - name: "Prepare Build"
        run: cmake -S . -B build

      - name: "Compile"
        run: cmake --build build -j

      - name: "Run Test"
        run: ./build/address_book_tests
